version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing SSH client"
      - apt-get update
      - apt-get install -y openssh-client

  pre_build:
    commands:
      - echo "Setting up SSH access"
      - chmod 400 deploy/my-ec2-key.pem
      - ls -al deploy/

  build:
    commands:
      - echo "Deploying to EC2..."
      - ssh -o StrictHostKeyChecking=no -i deploy/my-ec2-key.pem $SSH_USER@$EC2_IP "pkill -f app.py || true"
      - scp -o StrictHostKeyChecking=no -i deploy/my-ec2-key.pem -r * $SSH_USER@$EC2_IP:/home/ec2-user/
      - ssh -o StrictHostKeyChecking=no -i deploy/my-ec2-key.pem $SSH_USER@$EC2_IP "nohup python3 /home/ec2-user/app.py > output.log 2>&1 &"

artifacts:
  files:
    - '**/*'
